/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppMain: typeof import('./../layout/components/AppMain.vue')['default']
    BarChart: typeof import('./../views/dashboard/components/BarChart.vue')['default']
    Breadcrumb: typeof import('./../components/Breadcrumb/index.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElTree: typeof import('element-plus/es')['ElTree']
    FunnelChart: typeof import('./../views/dashboard/components/FunnelChart.vue')['default']
    Hamburger: typeof import('./../components/Hamburger/index.vue')['default']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    IEpCaretBottom: typeof import('~icons/ep/caret-bottom')['default']
    IEpClose: typeof import('~icons/ep/close')['default']
    IEpSetting: typeof import('~icons/ep/setting')['default']
    LangSelect: typeof import('./../components/LangSelect/index.vue')['default']
    Link: typeof import('./../layout/components/Sidebar/Link.vue')['default']
    Logo: typeof import('./../layout/components/Sidebar/Logo.vue')['default']
    Navbar: typeof import('./../layout/components/Navbar.vue')['default']
    PieChart: typeof import('./../views/dashboard/components/PieChart.vue')['default']
    RadarChart: typeof import('./../views/dashboard/components/RadarChart.vue')['default']
    RightPanel: typeof import('./../components/RightPanel/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollPane: typeof import('./../layout/components/TagsView/ScrollPane.vue')['default']
    Settings: typeof import('./../layout/components/Settings/index.vue')['default']
    Sidebar: typeof import('./../layout/components/Sidebar/index.vue')['default']
    SidebarItem: typeof import('./../layout/components/Sidebar/SidebarItem.vue')['default']
    SvgIcon: typeof import('./../components/SvgIcon/index.vue')['default']
    TagsView: typeof import('./../layout/components/TagsView/index.vue')['default']
  }
}
